sudo: required

dist: trusty

language: c

matrix:
  include:
  - os: linux
    compiler: gcc
    env: COMPILER=gcc-4.8
  - os: linux
    compiler: clang
    env: COMPILER=clang
  - os: osx
    compiler: clang
    env: COMPILER=clang
    before_install:
      - brew install libtool

install:
  - export CC="$COMPILER"
  - $CC --version

script:
  - make
  - make test

notifications:
  on_success: change
  on_failure: always
