sudo: required

dist: trusty

language: c

os:
- linux
- osx

compiler:
- gcc
- clang

matrix:
  allow_failures:
  - os: osx
  
script:
  - make
  - make test

notifications:
  on_success: change
  on_failure: always
