sudo: required

dist: trusty

language: c

matrix:
  include:
  - os: linux
    compiler: gcc
    env: COMPILER=gcc-4.8
    addons:
      apt:
        packages:
        - gcc-4.8-base
  - os: linux
    compiler: gcc
    env: COMPILER=gcc-4.9
    addons:
      sources:
        - ubuntu-toolchain-r-test
      apt:
        packages:
        - gcc-4.9-base
  - os: linux
    compiler: gcc
    env: COMPILER=gcc-5
    addons:
      sources:
        - ubuntu-toolchain-r-test
      apt:
        packages:
        - gcc-5-base
  - os: linux
    compiler: gcc
    env: COMPILER=gcc-6
    addons:
      sources:
        - ubuntu-toolchain-r-test
      apt:
        packages:
        - gcc-6-base
  - os: linux
    compiler: clang
    env: COMPILER=clang
  - os: osx
    compiler: clang
    env: COMPILER=clang
    before_install:
      - brew install libtool

install:
  - export CC="$COMPILER"
  - $CC --version

script:
  - make
  - make test

notifications:
  on_success: change
  on_failure: always
  
