language: c

os:
- linux
- osx

compiler:
- gcc
- clang

env:
  matrix:
  - LIBTOOL=
  - LIBTOOL=libtool-disabled

matrix:
  allow_failures:
  - os: osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libtool; fi
  
script:
  - make config
  - make
  - make test
  - cat test_*.log

notifications:
  on_success: change
  on_failure: always
